[build]
  publish = "build"
  command = "npm run build"
  functions_build_timeout = "20m"
  timeout = "30m"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.x"
