backend:
  name: git-gateway
  branch: main
  auth_scope: repo
  api_root: https://api.github.com
  commit_messages:
    create: '{{collection}}: 새로운 "{{slug}}" 생성'
    update: '{{collection}}: "{{slug}}" 업데이트'
    delete: '{{collection}}: "{{slug}}" 삭제'
    uploadMedia: '[미디어] "{{path}}" 업로드'
    deleteMedia: '[미디어] "{{path}}" 삭제'

# Git Gateway 설정
site_url: https://growithic.netlify.app
display_url: https://growithic.netlify.app
logo_url: https://growithic.netlify.app/assets/logo.png

# 미디어 파일 설정
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

# 로컬 개발 환경 설정
local_backend: true

# 언어 설정
locale: 'ko'

collections:
  # 프로젝트 컬렉션
  - name: "projects"
    label: "프로젝트"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string", required: true }
      - { label: "설명", name: "description", widget: "text", required: true }
      - { 
          label: "썸네일", 
          name: "thumbnail", 
          widget: "image",
          required: true,
          media_folder: "/assets/uploads"
        }
      - { 
          label: "좋아요", 
          name: "likes", 
          widget: "number", 
          default: 0,
          min: 0,
          required: true
        }
      - { label: "링크", name: "link", widget: "string", required: true }

  # 블로그 컬렉션
  - name: "blog"
    label: "블로그"
    folder: "src/data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string", required: true }
      - { label: "작성자", name: "author", widget: "string", required: true }
      - { 
          label: "작성일", 
          name: "date", 
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
          required: true
        }
      - { 
          label: "내용", 
          name: "content", 
          widget: "markdown",
          required: true
        }
      - { 
          label: "썸네일", 
          name: "thumbnail", 
          widget: "image",
          required: true,
          media_folder: "/assets/uploads"
        }

  # 페이지 컬렉션
  - name: "pages"
    label: "페이지"
    files:
      - file: "src/data/home.json"
        label: "홈페이지"
        name: "home"
        fields:
          - { label: "메인 제목", name: "title", widget: "string", required: true }
          - { label: "부제목", name: "subtitle", widget: "string", required: true }
          - { 
              label: "히어로 이미지", 
              name: "image", 
              widget: "image",
              required: true,
              media_folder: "/assets/uploads"
            }
          - { label: "CTA 버튼1", name: "cta_button_1", widget: "string", required: true }
          - { label: "CTA 버튼2", name: "cta_button_2", widget: "string", required: true }
