backend:
  name: git-gateway
  branch: main
  auth_scope: repo  # GitHub 저장소 접근 권한
  api_root: https://api.github.com  # GitHub API 엔드포인트
  commit_messages:
    create: '{{collection}}: 새로운 "{{slug}}" 생성'
    update: '{{collection}}: "{{slug}}" 업데이트'
    delete: '{{collection}}: "{{slug}}" 삭제'
    uploadMedia: '[미디어] "{{path}}" 업로드'
    deleteMedia: '[미디어] "{{path}}" 삭제'

# Git Gateway 설정
site_url: https://growithic.netlify.app
display_url: https://growithic.netlify.app
logo_url: https://growithic.netlify.app/assets/logo.png

# 미디어 파일 설정
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

# 로컬 개발 환경 설정
local_backend: true

# 언어 설정
locale: 'ko'

collections:
  - name: "projects"
    label: "프로젝트"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string", required: true }
      - { label: "설명", name: "description", widget: "text", required: true }
      - { 
          label: "썸네일", 
          name: "thumbnail", 
          widget: "image",
          required: true,
          media_folder: "/assets/uploads"
        }
      - { 
          label: "좋아요", 
          name: "likes", 
          widget: "number", 
          default: 0,
          min: 0,
          required: true
        }
      - { label: "링크", name: "link", widget: "string", required: true }
