backend:
  name: git-gateway
  branch: main

media_folder: "public/assets" # 업로드된 파일 경로
public_folder: "/assets"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/data/homepage.json"
        label: "Hero Section"
        name: "hero"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "CTA Button 1", name: "cta_button_1", widget: "string" }
          - { label: "CTA Button 2", name: "cta_button_2", widget: "string" }
